### ISSUE TITLE
link(s) to o'reily field guide

### ISSUE THREAD

**Issue by johnscancella** [18F/dev-environment#35]
I recently saw https://www.oreilly.com/ideas/field-guide-to-the-distributed-development-stack
and thought it might be a good idea to link to them in a lot of the areas in this guide. They also have it as a github repo here: https://github.com/odewahn/dds-field-guide

**Comment by mbland** [comment]
Hmm, that first link is behind an account wall. But the second one is apparently the source for http://sites.oreilly.com/odewahn/dds-field-guide/, which bears a spiritual resemblance to our own Guides. Agreed we should cross-link to it somehow; I've put it on the [Documentation Working Group](https://pages.18f.gov/wg-documentation/)'s agenda for tomorrow and announced it in our Slack channel. PRs are also always welcome, as well you know! :wink:

**Comment by johnscancella** [comment]
@mbland I just signed in with my google account, but yes the github should be exactly the same.
I will talk to my manager and see if I can spend some time on it, otherwise I will have to due it in my off time (which is very low at the moment due to house repair/improvements)
